AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Nested stacks - EC2 template.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Amazon EC2 Configuration'
        Parameters:
          - AmiID

    ParameterLabels:
      AmiID:
        default: 'Amazon Machine Image ID'

Parameters:
  EnvironmentType:
    Description: 'Specify the Environment type of the stack.'
    Type: String
    Default: Test
    AllowedValues:
      - Dev
      - Test
      - Prod
    ConstraintDescription: 'Specify either Dev, Test or Prod.'

  AmiID:
    Type: String
    Description: 'The ID of the AMI.'
    Default: ami-0aa7d40eeae50c9a9 #Amazon Linux 2 Kernel 5.10 AMI 2.0.20230119.1 x86_64 HVM gp2

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'The VPC ID'

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: 'The Subnet ID'
  
  WebServerInstanceProfile:
    Type: String
    Description: 'Instance profile resource ID'
  
  RDSEndpointAddress:
    Type: String
    Description: 'RDS Database Endpoint Address'
  RDSMasterUsername:
    Type: String
    Description: 'RDS Database Master User name'
  RDSMasterUserPassword:
    Type: String
    Description: 'RDS Database Master User Password'
  WebServerSecurityGroup:
    Type: String
    Description: 'RDS Database Master User Password'

Mappings:
  EnvironmentToInstanceType:
    Dev:
      InstanceType: t2.nano
    Test:
      InstanceType: t2.micro
    Prod:
      InstanceType: t2.small

Resources:
  # SSMIAMRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #               - ec2.amazonaws.com
  #           Action:
  #             - sts:AssumeRole
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  # WebServerInstanceProfile:
  #   Type: AWS::IAM::InstanceProfile
  #   Properties:
  #     Path: /
  #     Roles:
  #       - !Ref SSMIAMRole
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref WebServerInstanceProfile
      ImageId: !Ref AmiID
      InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref EnvironmentType, InstanceType]
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref EnvironmentType, webserver ] ]
        
    # CreationPolicy:
    #   ResourceSignal:
    #     Count: 1
    #     Timeout: PT10M


  # WebServerEIP:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc
  #     InstanceId: !Ref WebServerInstance
  #   DependsOn:
  #     - WebServerInstance

# Outputs:
#   WebServerPublicDNS:
#     Description: 'Public DNS of EC2 instance'
#     Value: !GetAtt WebServerInstance.PublicDnsName

#   WebServerElasticIP:
#     Description: Elastic IP associated with the web server EC2 instance
#     Value: !Ref WebServerEIP

#   WebsiteURL:
#     Value: !Sub http://${WebServerEIP}
#     Description: Application URL