AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation - Nested stacks - RDS MYSQL template.
Parameters:
  SubnetId1:
    Type: AWS::EC2::Subnet::Id
    Description: 'The Subnet ID'
  SubnetId2:
    Type: AWS::EC2::Subnet::Id
    Description: 'The Subnet ID'
Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: my-db-subnet-group
      DBSubnetGroupDescription: my-db-subnet-group
      SubnetIds: 
        - !Ref SubnetId1
        - !Ref SubnetId2
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 10
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: "5.7"
      DBInstanceIdentifier: my-db-instance
      DBName: mydatabase
      MasterUsername: myusername
      MasterUserPassword: mypassword
      DBSubnetGroupName: !Ref DBSubnetGroup
